id: 1
dataset: "flower_data"
seed: 0
device: "cuda:2"
backbone: "resnet50"
weights_backbone: null
task: "classification"
model: "resnet50"
weights: null
opt: "sgd"
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
norm_weight_decay: null
bias_weight_decay: null
label_smoothing: 0.0
lr_scheduler: "steplr"
lr_step_size: 30
lr_steps: [16, 22]
lr_gamma: 0.1
lr_min: 0.0
aspect_ratio_group_factor: 3
rpn_score_thresh: null
trainable_backbone_layers: null
data_augmentation: "hflip"
sync_bn: False
test_only: False
use_deterministic_algorithms: False
random_erase: 0.0
auto_augment: null
ra_magnitude: 9
augmix_severity: 3
interpolation: "bilinear"
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224
amp: False
clip_grad_norm: null
ra_sampler: False
ra_reps: 3
train_split: 0.75
train_set: "val"
backend: "PIL"
use_v2: False
resume: ""
start_epoch: 0
epochs: 1
batch_size: 32
workers: 16
print_freq: 100
out_path: "./outs/fl/"
log_path: "logs/"
weight_path: "weights/"
log_name: "FL.log"