local_epochs: 1
batch_size: 64 
criterion: torch.nn.CrossEntropyLoss
criterion_config:
  - reduction: 'none' 
    beta: 2 
optimizer: torch.optim.SGD
optim_config: 
  - lr: 0.01
    momentum: 0.9
dataset_name: 'MNIST'