id: 0
dataset: "voc_det"
seed: 0
device: "cuda:1"
backbone: "resnet50"
backbone_weights: null
task: "detection"
model: "maskrcnn_resnet50_fpn_v2"
weights: null
opt: "sgd"
lr: 0.02
momentum: 0.9
weight_decay: 0.0001
norm_weight_decay: null
bias_weight_decay: null
label_smoothing: 0.0
lr_scheduler: "multisteplr"
lr_step_size: 8
lr_steps: [36, 43]
lr_gamma: 0.1
lr_min: 0.0
aspect_ratio_group_factor: 3
rpn_score_thresh: null
trainable_backbone_layers: null
data_augmentation: "hflip"
sync_bn: False
test_only: False
use_deterministic_algorithms: False
random_erase: 0.0
auto_augment: null
ra_magnitude: 9
augmix_severity: 3
interpolation: "bilinear"
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224
amp: False
clip_grad_norm: null
ra_sampler: False
ra_reps: 3
train_split: 0.0
train_set: "train"
backend: "PIL"
use_v2: False
resume: ""
start_epoch: 0
epochs: 1
batch_size: 4
workers: 16
print_freq: 100
out_path: "./outs/fl/"
log_path: "logs/"
weight_path: "weights/"
log_name: "FL.log"